########## These all have default values as shown

location.SidoCd: 41, 경기도
#	- 11, 서울특별시
#	- 26, 부산광역시
#	- 27, 대구광역시
#	- 28, 인천광역시
#	- 29, 광주광역시
#	- 30, 대전광역시
#	- 31, 울산광역시
#	- 36, 세종특별자치시
#	- 41, 경기도
#	- 42, 강원도
#	- 43, 충청북도
#	- 44, 충청남도
#	- 45, 전라북도
#	- 46, 전라남도
#	- 47, 경상북도
#	- 48, 경상남도
#	- 50, 제주특별자치도

location.SiguCd:
    - 820, 가평군
#    - 281, 고양시 덕양구
#    - 471, 고양시 덕양구
#    - 473, 고양시 일산구
#    - 285, 고양시 일산동구
#    - 287, 고양시 일산서구
#    - 290, 과천시
#    - 210, 광명시
#    - 790, 광주군
#    - 610, 광주시
#    - 310, 구리시
#    - 410, 군포시
#    - 570, 김포시
#    - 360, 남양주시
#    - 250, 동두천시
#    - 190, 부천시
#    - 197, 부천시 소사구
#    - 199, 부천시 오정구
#    - 195, 부천시 원미구
#    - 135, 성남시 분당구
#    - 131, 성남시 수정구
#    - 133, 성남시 중원구
#    - 113, 수원시 권선구
#    - 117, 수원시 영통구
#    - 111, 수원시 장안구
#    - 115, 수원시 팔달구
#    - 390, 시흥시
#    - 273, 안산시 단원구
#    - 271, 안산시 상록구
#    - 860, 안성군
#    - 550, 안성시
#    - 173, 안양시 동안구
#    - 171, 안양시 만안구
#    - 630, 양주시
#    - 830, 양평군
#    - 730, 여주군
#    - 800, 연천군
#    - 370, 오산시
#    - 490, 용인시
#    - 463, 용인시 기흥구
#    - 465, 용인시 수지구
#    - 461, 용인시 처인구
#    - 430, 의왕시
#    - 150, 의정부시
#    - 530, 이천시
#    - 500, 이천시
#    - 480, 파주시
#    - 510, 파주시
#    - 220, 평택시
#    - 650, 포천시
#    - 450, 하남시
#    - 750, 화성군
#    - 590, 화성시